//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_completion.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class User:DbContext
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int MobileNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
   
}
